language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sulagnasinha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sulagnasinha/docker-react npm run test